name: Terraform CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GCP credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS" > /tmp/key.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: iac/terraform

      - name: Plan Terraform changes
        run: terraform plan -out=tfplan
        working-directory: iac/terraform

      - name: Apply Terraform changes
        run: terraform apply -auto-approve tfplan
        working-directory: iac/terraform

      - name: Clean up Terraform files
        run: rm -rf .terraform tfplan
        working-directory: iac/terraform

      - name: Store Terraform state
        run: |
          gsutil cp terraform.tfstate gs://${{ secrets.TERRAFORM_BUCKET }}/terraform.tfstate
        working-directory: iac/terraform
        if: always()